# Generated by Django 3.2.12 on 2022-03-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='managerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerId', models.CharField(max_length=50)),
                ('managerPw', models.CharField(max_length=50)),
                ('lastLogin', models.DateTimeField()),
                ('enrolldate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='manageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerName', models.CharField(max_length=50)),
                ('managerAddress', models.CharField(max_length=100)),
                ('managerPhone', models.CharField(max_length=20)),
                ('managerNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chabinuManager.manageraccount')),
            ],
        ),
    ]
